export {
  advanceGame,
  compileSceneControlFlow,
  getChoices,
  getLocalizedRuntimeErrorMessage,
  selectChoice,
  startGame,
  startGameAtScene,
  validateSceneControlFlow,
  type GameRuntime,
  type RuntimeCharacterState,
  type RuntimeErrorCode,
  type RuntimeLoopFrame,
  type RuntimeVariables,
} from './gameRuntime';

export {
  areGameRuntimeSnapshotsEqual,
  createGameRuntimeSnapshot,
  GAME_RUNTIME_SNAPSHOT_VERSION,
  isGameRuntimeSnapshot,
  isSaveableGameRuntime,
  restoreGameRuntimeSnapshot,
  type GameRuntimeSnapshot,
  type CurrentGameRuntimeSnapshot,
  type LegacyGameRuntimeSnapshot,
  type SaveableGameRuntime,
} from './gameRuntimeSnapshot';

export {
  isLogicCondition,
  isLogicOperand,
  isLogicValue,
  isLogicVariableName,
  MAX_AUTOMATIC_STEPS_PER_ADVANCE,
  MAX_LOGIC_NESTING_DEPTH,
  MAX_LOGIC_STRING_BYTES,
  MAX_REPEAT_COUNT,
  MAX_RUNTIME_VARIABLE_BYTES,
  MAX_RUNTIME_VARIABLES,
  MAX_VARIABLE_NAME_BYTES,
  projectLogicVariableNames,
  utf8ByteLength,
  validateProjectLogicVariableBudget,
} from './logicValidation';

export type {
  BackgroundNode,
  BgmNode,
  CgGalleryDocument,
  CgGalleryPageDocument,
  CharacterNode,
  CharacterPosition,
  CharacterSlot,
  ChoiceNode,
  ChoiceOption,
  DialogueNode,
  LogicComparisonOperator,
  LogicCondition,
  LogicElseNode,
  LogicEndIfNode,
  LogicEndRepeatNode,
  LogicIfNode,
  LogicOperand,
  LogicRepeatNode,
  LogicValue,
  ProjectDocument,
  SceneDocument,
  SceneJumpNode,
  SceneNode,
  StartScreenDocument,
  VariableChangeNode,
  VariableSetNode,
  VideoNode,
} from './projectTypes';
